import {levels,phases,locate,format} from './engine.js';
const $=id=>document.getElementById(id), KEY='runprogress-v1';
let saved={};try{saved=JSON.parse(localStorage.getItem(KEY))||{};}catch{}
let level=Number.isInteger(saved.level)&&saved.level>=0&&saved.level<levels.length?saved.level:0;
let list=phases(levels[level]),total=list.reduce((a,p)=>a+p.seconds,0);
let elapsed=Number.isFinite(saved.elapsed)?Math.max(0,Math.min(saved.elapsed,total)):0;
let counts=levels.map((_,i)=>Number.isInteger(saved.counts?.[i])&&saved.counts[i]>=0?saved.counts[i]:0);
let skipped=!!saved.skipped,recorded=!!saved.recorded,running=false,anchor=0,base=elapsed,lastIndex=locate(list,elapsed).index,audio,wake;
$('sound').checked=saved.sound!==false;$('vibration').checked=saved.vibration!==false;
function persist(){try{localStorage.setItem(KEY,JSON.stringify({level,elapsed,counts,skipped,recorded,sound:$('sound').checked,vibration:$('vibration').checked}));}catch{$('notice').textContent='Salvataggio non disponibile: i progressi potrebbero andare persi alla chiusura.';}}
function render(){const pos=locate(list,elapsed),p=list[pos.index],done=!p;$('phase').textContent=p?.name||'Sessione conclusa';$('phaseHint').textContent=p?.hint||(skipped?'Hai saltato una o più fasi. Nessun completamento registrato.':'Hai concluso il tuo allenamento.');$('remaining').textContent=format(pos.left);$('phaseCount').textContent=done?'HAI FINITO':`FASE ${pos.index+1} DI ${list.length}`;$('progress').max=total;$('progress').value=elapsed;$('elapsed').textContent=`${format(elapsed)} trascorsi`;$('total').textContent=`${format(total)} totali`;$('status').textContent=done?'CONCLUSO':running?'IN CORSO':elapsed?'IN PAUSA':'PRONTO';$('play').textContent=running?'Pausa':elapsed?'Riprendi':'Inizia allenamento';$('play').disabled=done;$('skip').disabled=done;$('level').disabled=running||elapsed>0&&elapsed<total;$('levelLabel').textContent=`LIVELLO ${String(level+1).padStart(2,'0')}`;$('history').textContent=`${counts[level]} sessioni completate in questo livello`;}
async function enableAudio(){if(!$('sound').checked)return;try{const AC=window.AudioContext||window.webkitAudioContext;if(!AC)throw Error();audio??=new AC();await audio.resume();$('audioStatus').textContent=audio.state==='running'?'Audio attivo. Controlla che il segnale sia udibile.':'Audio sospeso: premi Prova avvisi.';}catch{$('audioStatus').textContent='Audio non disponibile. Il timer funziona con gli avvisi visivi.';}}
function signal(){if($('vibration').checked&&navigator.vibrate)navigator.vibrate([150,80,150]);if(!$('sound').checked||!audio||audio.state!=='running')return;[0,.22,.44].forEach((delay,i)=>{const o=audio.createOscillator(),g=audio.createGain(),t=audio.currentTime+delay;o.frequency.value=i===2?880:660;g.gain.setValueAtTime(0,t);g.gain.linearRampToValueAtTime(.2,t+.015);g.gain.exponentialRampToValueAtTime(.001,t+.16);o.connect(g);g.connect(audio.destination);o.start(t);o.stop(t+.18);o.onended=()=>{o.disconnect();g.disconnect();};});}
async function lock(){try{if('wakeLock' in navigator&&document.visibilityState==='visible'){const candidate=await navigator.wakeLock.request('screen');if(running)wake=candidate;else await candidate.release();}}catch{}}
function unlock(){wake?.release().catch(()=>{});wake=null;}
function tick(){if(!running)return;elapsed=Math.min(total,base+(performance.now()-anchor)/1000);const index=locate(list,elapsed).index;if(index!==lastIndex){lastIndex=index;signal();persist();}if(elapsed>=total){running=false;unlock();if(!skipped&&!recorded){counts[level]++;recorded=true;}persist();}render();}
function pause(message){tick();running=false;unlock();persist();render();if(message)$('notice').textContent=message;}
$('play').onclick=()=>{if(running){pause();return;}if(elapsed>=total)return;enableAudio().then(()=>{if(running)signal();});base=elapsed;anchor=performance.now();running=true;lock();$('notice').textContent='Tieni l’app visibile e lo schermo acceso durante la sessione.';persist();render();};
$('skip').onclick=()=>{tick();if(elapsed>=total)return;skipped=true;const p=locate(list,elapsed);elapsed=p.start+list[p.index].seconds;base=elapsed;anchor=performance.now();lastIndex=locate(list,elapsed).index;signal();if(elapsed>=total){running=false;unlock();}persist();render();};
$('reset').onclick=()=>{if(elapsed>0||running){if(!confirm('Ricominciare questa sessione da zero? I completamenti precedenti restano salvati.'))return;}running=false;unlock();elapsed=base=0;skipped=recorded=false;lastIndex=0;persist();render();$('notice').textContent='Sessione pronta. Premi Inizia allenamento.';};
$('level').innerHTML=levels.map((l,i)=>`<option value="${i}">${l.name}</option>`).join('');$('level').value=level;
function recipe(){const l=levels[level];$('recipe').textContent=`5 min iniziali + ${l.reps} × (${format(l.run)} corsa + ${format(l.walk)} cammino) + 5 min finali.`;}
$('level').onchange=()=>{level=Number($('level').value);list=phases(levels[level]);total=list.reduce((a,p)=>a+p.seconds,0);elapsed=base=0;skipped=recorded=false;lastIndex=0;recipe();persist();render();};
$('test').onclick=async()=>{await enableAudio();signal();};$('sound').onchange=()=>{persist();if($('sound').checked)enableAudio();};$('vibration').onchange=persist;
document.addEventListener('visibilitychange',()=>{if(document.hidden&&running)pause('L’app non era visibile: sessione in pausa. Controlla la fase e premi Riprendi.');});
window.addEventListener('pagehide',()=>{if(running)pause();else persist();});
setInterval(tick,200);setInterval(()=>{if(running)persist();},1000);
recipe();render();if(elapsed>0&&elapsed<total)$('notice').textContent='Sessione recuperata in pausa. Controlla la fase e premi Riprendi.';
if('serviceWorker' in navigator){navigator.serviceWorker.register('./sw.js').then(async reg=>{await navigator.serviceWorker.ready;$('offline').textContent='Pronta per l’uso offline su questo dispositivo.';reg.addEventListener('updatefound',()=>{const worker=reg.installing;worker?.addEventListener('statechange',()=>{if(worker.state==='installed'&&navigator.serviceWorker.controller)$('offline').textContent='Aggiornamento pronto: chiudi tutte le finestre dell’app e riaprila dopo la sessione.';});});}).catch(()=>{$('offline').textContent='Offline non disponibile: apri l’app via HTTPS o localhost.';});}else $('offline').textContent='Questo browser non supporta la modalità offline.';
